### ISSUE TITLE
Retrieve waterlevel timeseries

### ISSUE THREAD

**Issue by giosans** [Deltares/eo-bathymetry#10]
Buoys location can be retrieved from here: http://kml.deltares.nl/kml/rijkswaterstaat/waterbase/Download water level time series for nearest buoys

Data itself has to be downloaded from here: http://live.waterbase.nl or from Matroos http://matroos.deltares.nl/timeseries/start/

**Comment by gena** [comment]
Imported time series for five stations, from @ckrogers: https://code.earthengine.google.com/c1a53f65a2060c765fd3b57ca4533a63

**Comment by ckrogers** [comment]
notebook which converts .csv files to .shp commited to https://github.com/Deltares/eo-bathymetry/blob/master/notebooks/Buoy_csv2shp.ipynb
